version: '3.3'
services:
  bladwijzer:
    container_name: Bladwijzer
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./dockerfile
    depends_on:
      - selenium
      - db
    networks:
      - app_network

  selenium:
    container_name: SeleniumStandalone
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - app_network

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "Password1!"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app_network

volumes:
  db:

networks:
  app_network:
    driver: bridge
